const fs = require('fs');
const path = require('path');
const CommitMessageFormatter = require('./formatter');

try {
  // generated by git
  const commitMsgFile = process.argv[2]; 
  if (!commitMsgFile) {
    console.error('❌ No commit message file provided');
    process.exit(0);
  }

  // Validate file exists
  if (!fs.existsSync(commitMsgFile)) {
    console.error(`❌ Commit message file not found: ${commitMsgFile}`);
    process.exit(0);
  }

  // 
  const formatter = new CommitMessageFormatter();
  
  let msg;
  try {
    msg = fs.readFileSync(commitMsgFile, 'utf8');
  } catch (error) {
    console.error(`❌ Failed to read commit message file: ${error.message}`);
    process.exit(0);
  }
  
  // 
  const versionRegex = /^v\d+\.\d+\.\d+\s+/;
  if (versionRegex.test(msg)) {
    msg = msg.replace(versionRegex, '');
  }
  
  // 
  msg = msg.trim();
  
  // 
  if (!msg || msg.startsWith('# Please enter') || msg.includes('Lines starting')) {
    msg = 'Auto commit';
  }
  
  // 
  const formattedMessage = formatter.formatMessage(msg);
  
  try {
    fs.writeFileSync(commitMsgFile, formattedMessage, 'utf8');
  } catch (error) {
    console.error(`❌ Failed to write formatted commit message: ${error.message}`);
    process.exit(0);
  }
  
} catch (e) {
  console.error('❌ Failed to format commit message:', e.message);
  // Don't fail the commit, just log error
}
